name: No PRs on main

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: read

jobs:
  reject-main-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Check base branch
        env:
          # Explicitly fallback to an empty string if it doesn't exist
          TARGET_BRANCH: ${{ github.base_ref || ''}}
        run: |
          if [ "$TARGET_BRANCH" = "main" ]; then
            echo "PR target branch is main."
            exit 0
          fi
